version: '3'
services:
  frontend:
    build:
      context: ./uii
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build:
      context: ./Engine
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:1234@db:3307/drs

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: drs
    ports:
      - '3307:3306'
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: